### ISSUE TITLE
Add support for webkitNotifications?

### ISSUE THREAD

**Issue by xiangwangfeng** [djyde/WebShell#38]

**Comment by 0xWDG** [comment]
We do support (local) HTML5 Notifications please see [the examples](https://github.com/djyde/WebShell/blob/master/Tests/Notifications.html)

External (Safari) notifications via apple's APN server are not supported, because this is restricted to a app pushed to the Mac AppStore wich WebShell itself isn't

**Comment by xiangwangfeng** [comment]
[Standard html5 notification](http://caniuse.com/#feat=notifications) is supported from chrome45,IE8,FireFox42.

So in order to support more browser, some web-app may decide to use navigator.webkitNotification instead of standard html5 Notification in old browser. Isn't it better to support more  nonstandard notification api?

**Comment by 0xWDG** [comment]
What's the difference between navigator.webkitNotification and the official one.

We fully support the html5 notification

**Comment by 0xWDG** [comment]
@djyde what do you think?

**Comment by djyde** [comment]
`webkitNotification` was only supported by Android Browser. I think it unnecessary to be supported in WebShell
