### ISSUE TITLE
Prepare for Swift 3 Support

### ISSUE THREAD

**Issue by 0xWDG** [djyde/WebShell#61]
Created https://github.com/djyde/WebShell/tree/Swift30
It's running on Swift 3

Some things need to be fixed
- [x] Download does not work (because we don't may subscript AnyObject)
- [x] Media keys does not work
- [x] func Download() does not work because of URLSession (NSURLSession)
- [x] Contextmenu does not work.
- [x] ... we need to find out.

<s>If you are using Xcode-Beta 8.0.</s>

Please remove the WebShell directory.
then open the terminal and run this command.
<s>`git clone https://github.com/djyde/WebShell.git -b Swift30`</s>
This will clone the (experimental) Swift 3.0 version of WebShell

If this works for you please report it to us.

**Comment by wdg** [comment]
Created https://github.com/djyde/WebShell/tree/Swift30
I'ts running on Swift 3

Some things need to be fixed
- [ ] Download does not work (because we don't may subscript AnyObject)
- [ ] Mediakeys does not work
- [ ] func Download() does not work because of URLSession (NSURLSession)
- [ ] ... we need to find out.

**Comment by 0xWDG** [comment]
Fix for contextmenu is coming 👍 
Found the solution

**Comment by 0xWDG** [comment]
@djyde Finished \o/ 👍

**Comment by 0xWDG** [comment]
See: #64

**Comment by djyde** [comment]
Great work!
