### ISSUE TITLE
Build succeeds, but app stalls

### ISSUE THREAD

**Issue by tliebig** [djyde/WebShell#62]
Hi,

I was able to successfully build the app the Xcode, but the app exits right after starting.

When running the app through Xcode, I get the following message:
`APP_NAME[13909:905406] Unable to find class: WebShell.WebShellMediaKeysSupport, exiting`

I've tried it both with MediaKeys `true` and `false` in settings.swift, but this did not make a difference.

Any pointers as to what else I could try?

**Comment by djyde** [comment]
Did u use the latest version?

**Comment by 0xWDG** [comment]
Hi,

I have a question to you.
Are you using Xcode beta (version 8.0).
Then Yes, I'll now it but we didn't optimize all the code for Swift 3.
Since there were between beta 1, and beta 6 a lot of major changes in the swift 3 compiler.

Please report the Xcode version and the build number.
Second are you using Swift 2.x or Swift 3?

Thanks in advance.

**Comment by 0xWDG** [comment]
If you are using Xcode-Beta 8.0.

Please remove the WebShell directory.
then open the terminal and run this command.
`git clone https://github.com/djyde/WebShell.git -b Swift30`
This will clone the (experimental) Swift 3.0 version of WebShell

If this works for you please report it to us.
Please refer to #61 for all the Swift 3 issues

**Comment by tliebig** [comment]
Xcode is Version 7.3.1 (7D1014).

About Swift I'm not sure. I downloaded the latest WebShell via https://github.com/djyde/WebShell > Clone or Download > Download.

First had quite a bunch of errors when building, but that was due to unknowingly using Xcode 6.4. Upgraded to XCode 7.3, re-downloaded webshell to start from scratch, and edited settings.swift. Building works fine (with no errors), but the app stalls right after starting.

Editing the settings.swift included some MediaKey settings. I initially set the to "false", but both "false" and "true" result in the same error.

System ist El Capitan 10.11.6 (15G31), German localization, on a MacBook Air mid 2011.

Is there anything else I can try?

**Comment by tliebig** [comment]
Found the error: The error occurs as soon as I rename the project from "WebShell" to "my.webservice.com".

Looks like 
`easyjob.zebra.de[3900:121386] Unable to find class: WebShell.WebShellMediaKeysSupport,`
does not get refactored to `easyjob.zebra.de.WebShellMediaKeysSupport`

**Comment by 0xWDG** [comment]
Can you please ZIP your project, and then upload it to somewhere?.
So we can check for errors.

**Comment by 0xWDG** [comment]
Please see: https://github.com/djyde/WebShell/blob/master/WebShell/Info.plist#L37 have you updated that line to your project/class name? `easyjob.zebra.de` or the project name.
please try changing that setting.

**Comment by tliebig** [comment]
I think you meant line 39 - at least that's what it was for me. Changing it to my projekt name "easyjob.zebra.de" didn't work, though. I suppose the dots might mess up XCode.

The ZIP prior to changing the line is available at http://downloads.beta.zebra.de/57cdc8277e916.zip (221.1 KB, valid till 2016-09-19). 

I just followed https://github.com/djyde/WebShell/wiki/How-to-build-a-WebShell-based-application and think right at step 2 the refactoring fails in my case.

**Comment by 0xWDG** [comment]
Ok, Thanks.

I've got 2 solutions for your case.

First is the simple one:
<img width="566" alt="solution 1" src="https://cloud.githubusercontent.com/assets/1290461/18256193/51141ca2-73b2-11e6-89b6-41809331f5e0.png">

Second is maybe better (Because a appname like `de.zebra.easyjob.app` is a little bit weird).
<img width="255" alt="step 1" src="https://cloud.githubusercontent.com/assets/1290461/18256201/6686e72c-73b2-11e6-99cc-a62915d58322.png">
<img width="562" alt="step 2" src="https://cloud.githubusercontent.com/assets/1290461/18256203/69da1a0c-73b2-11e6-88bc-ca34a498e3f2.png">

Please let me know if it has helped you!

---

"." and " " need to be replaced to _

**Comment by tliebig** [comment]
Alright, that did the job - thanks alot. 

Maybe the tutorial under https://github.com/djyde/WebShell/wiki/How-to-build-a-WebShell-based-application should be updated to include having to fix the info.plist after renaming the project in step 2?

**Comment by 0xWDG** [comment]
Great that it helps!

I definitely will update the tutorial.
I'm still a bit busy with squashing some Swift 3.0 bugs..
I hope I've got enough time to fix it tomorrow 😊

Kind Regards/Vriendelijke Groet,
Wesley de Groot.

Disclaimer: http://www.wdgwv.com/disclaimer

**Comment by 0xWDG** [comment]
Wiki is now up-to-date: https://github.com/djyde/WebShell/wiki/How-to-build-a-WebShell-based-application

Closing this issue.
